"""empty message

Revision ID: 363100915190
Revises: e982091e9e05
Create Date: 2020-09-15 11:26:51.265966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363100915190'
down_revision = 'e982091e9e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
